### ISSUE TITLE
adding ACL service

### ISSUE THREAD

**Issue by fezrul** [nasrulhazim/kong-gateway-php-client#6]
// Enabling the consumer to ACL services in plugin.php

    public function group($data)
    {
        $parameters = array_merge([
           
        ], $data);

        return [
            'form_params' => $parameters,
        ];
    }

    public function enableConsumerAcl($consumer): string
    {
        return $this->consumerPath($consumer).'/acls';
    }

    public function enableForAcl($consumer, $data)
    {
        return $this->response(
            $this->client()
                ->post(
                    $this->enableConsumerAcl($consumer),
                    $this->group($data)
                )
        );
    }

//usage : 

//enable plugin acl consumer

    $group = 'consumer'.$name;
    $data = [
        'name' => 'acl',
        'config.allow' => $group,
        'config.hide_groups_header' => 'true',
    ];
    $plugin['acl-consumer'] = kong()->plugin()->enableForService($name,$data,'acl');

//enable plugin acl provider

    $group = 'provider'.$name;
    $data = [
    
        'name' => 'acl',
        'config.allow' => $group,
        'config.hide_groups_header' => 'true',
    ];
    $plugin['acl-provider'] = kong()->plugin()->enableForService($name,$data,'acl');

**Comment by nasrulhazim** [comment]
@fezrul , any reference to Kong Hub documentation?

**Comment by fezrul** [comment]
> 
> 
> @fezrul , any reference to Kong Hub documentation?

oo i think just now I look at this samples :

https://docs.konghq.com/hub/kong-inc/acl/

**Comment by nasrulhazim** [comment]
@fezrul , added ACL Plugin as in [v1.3.1](https://github.com/nasrulhazim/kong-gateway-php-client/releases/tag/1.3.1). 

Available methods as in [wiki](https://github.com/nasrulhazim/kong-gateway-php-client/wiki/ACL)
