### ISSUE TITLE
error when try retrive ACL by username

### ISSUE THREAD

**Issue by fezrul** [nasrulhazim/kong-gateway-php-client#7]
PHP Fatal error:  

Declaration of KongGateway\AdminAPI\Plugin\TrafficControl\ACL::show($consumer, $identifier) 
must be compatible with KongGateway\AdminAPI\Base::show($identifier) 

in /var/www/html/apim/vendor/nasrulhazim/kong-gateway-php-client/src/AdminAPI/Plugin/TrafficControl/ACL.php on line 43

  at vendor/nasrulhazim/kong-gateway-php-client/src/AdminAPI/Plugin/TrafficControl/ACL.php:43
     39▕      * Retrieve Consumer by ID.
     40▕      *
     41▕      * @see https://docs.konghq.com/hub/kong-inc/acl/#retrieve-consumer-by-id
     42▕      */
  ➜  43▕     public function show($consumer, $identifier)
     44▕     {
     45▕         return $this->response(
     46▕             $this->client()->get($this->consumerPath($consumer).'/acls/'.$identifier)
     47▕         );

it seam that funcyion for show only accept 1 declaration

**Comment by nasrulhazim** [comment]
@fezrul , ah ok. forgot the base class has the interface to be comply with. Will update.

**Comment by nasrulhazim** [comment]
Resolved as in 18198a957bd66bbdd93429470ad61630dd7f0ee1

@fezrul , use `showConsumerById` instead of `show` method. Will release another version by today, together with new plugin will be add - Request Termination.
